apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: k8s-secret
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: fpqlcmggrpfdhmi0uc3k
        property: chain
    - secretKey: tls.key
      remoteRef:
        key: fpqlcmggrpfdhmi0uc3k
        property: privateKey
